---
title: "Pohatu Penguins Monitoring Data Analysis"
author: "Rachel Hickcox"
date: "2022"
email: "rphickcox@gmail.com"
editor_options: 
  chunk_output_type: console
---

### Load packages
```{r pkg, eval=TRUE, message=FALSE, warning=FALSE, cache=FALSE}
pkgs <- c("rgdal", "rgeos", "raster", "knitr", "kableExtra", "broom", 
          "readxl", "flextable", "terra", "googlesheets4", "googledrive", "lubridate", "tidyverse")
new.packages <- pkgs[!(pkgs %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
invisible(lapply(pkgs, library, character.only = TRUE))
rm(list = c("pkgs", "new.packages"))
options(scipen = 999)
```

### Connecting to Google Drive
```{r googledrive}
drive_auth(email = "pohatumonitoring@gmail.com")

drive_download(file = "https://docs.google.com/spreadsheets/d/1AKbYixeUF_LM8SEknA49wvnERDVeZFWEIAilM75m0nw", 
               overwrite = TRUE, 
               path = "Monitoring.xlsx")
monitor <- read_excel("Monitoring.xlsx")

drive_download(file = "https://docs.google.com/spreadsheets/d/1qh6zAXgVokfdx4WjjSls8qh4tAfEOL-bO3xg3CvRY44", 
               overwrite = TRUE,
               path = "Nest ID.xlsx")
nestid <- read_excel("Nest ID.xlsx")

drive_download(file = "https://docs.google.com/spreadsheets/d/16c4c5nXbz_PFf7iyN2DG7fExsi4P5uP-NSYAbCDX1rc", 
               overwrite = TRUE, 
               path = "Bird ID.xlsx")
birdid <- read_excel("Bird ID.xlsx")
```

### Setup
```{r setup}
# Dates
tdt <- floor_date(today(), "weeks", week_start = 1)
tdt_d <- format(tdt, "%d-%m-%Y")
tdt_s <- as.numeric(str_replace_all(as.character(tdt), pattern = "-", ""))
yr <- ifelse(month(today()) > 8, year(today()), year(today())-1)
start <- floor_date(as.Date(paste0("01-08-", yr), "%d-%m-%Y"), "weeks", week_start = 1)
dates_df <- seq(start, today(), 7)
```

### Nests summary
```{r nests}
# Nest coords 
nestid_coord <- nestid %>%
  tidyr::separate(Location, into = c("Lat", "Long"), ",") %>%
  dplyr::select(`Nest ID`, Lat, Long) %>%
  mutate(Lat = as.numeric(Lat), Long = as.numeric(Long))

nests <- monitor %>%
  mutate(Eggs = ifelse(is.na(Eggs), 0, as.numeric(Eggs)), 
         Chicks = ifelse(is.na(Chicks), 0, as.numeric(Chicks))) %>%  
  group_by(`Nest ID`) %>%
  arrange(`Nest ID`, DateTime) %>%
  mutate(n = row_number()) %>%
  mutate(n1 = ifelse(`Nest activity` == "Eggs/Chicks present", n, NA)) %>%
  filter(n >= min(n1, na.rm = TRUE)-1 | n == max(n1, na.rm = TRUE)+1) %>%
  mutate(Date_last = lag(DateTime), .before = DateTime) %>% 
  mutate(`Nest activity` = ifelse(Interaction == "Uplifted", "Uplifted",`Nest activity`)) %>% 
  #dplyr::select(-c(n, n1)) %>%
  mutate(.after = 2,
         DateTime = as.Date(DateTime),
         Week = week(DateTime),
         Date_last = difftime(as.Date(DateTime), as.Date(Date_last), units = "days"), 
         Est_LayDate = as.Date(min(DateTime, na.rm = TRUE))) %>%
  mutate(.after = Est_LayDate, Est_HatchDate = Est_LayDate + 35) %>% 
  dplyr::select(`Nest ID`, Date_last:Est_HatchDate, `Nest activity`:`Adult 1`, 
                `Adult 2`, Eggs:`Chick 1 weight`, `Chick 2 ID`:`Chick 2 weight`, n, n1) %>%
  mutate(Status = ifelse(Eggs > 0, "Eggs", NA), 
         Status = ifelse(Chicks > 0, "Chicks", Status), 
         .before = 2) %>% 
  left_join(nestid_coord, by = "Nest ID") %>% 
  mutate(n2 = lag(Chicks)) %>% 
  group_by(`Nest ID`, `Nest activity`) %>% 
  mutate(`Nest activity` = ifelse(`Nest activity` == "FAILED" & 
                                    duplicated(`Nest activity`), 
                                  NA, `Nest activity`), 
         Status = ifelse(is.na(`Nest activity`), NA, Status)) %>% 
  group_by(`Nest ID`) %>% 
  mutate(Status = ifelse(is.na(n1) & n2 > 0, "Fledged", Status),
         Status = ifelse(`Nest activity` == "FAILED" & !is.na(Status), 
                         "Failed", Status), 
         Status = ifelse(`Nest activity` == "Uplifted", `Nest activity`, Status),
         Status = ifelse(`Nest activity` == "Empty" & 
                           lag(`Nest activity`) == "Uplifted", NA, Status),
         nn = ifelse(lag(`Nest activity`) == "FAILED" & 
                       `Nest activity` == "Empty", "R", NA), 
         nn = unlist(nn)) %>%  
  filter(!is.na(Status), is.na(nn)) %>% 
  select(-c(n, n1, n2, nn))

# Failed nests 
failed_nests <- nests %>%
  filter(Status == "Failed") %>% # | Status == "Uplifted") %>%
  dplyr::select(`Nest ID`, `Nest activity`, DateTime) %>% 
  group_by(`Nest ID`) %>% 
  arrange(`Nest ID`, DateTime) %>% 
  left_join(nestid_coord, by = "Nest ID")
#clipr::write_clip(failed_nests)

# Nests with eggs
eggs <- nests %>% 
  filter(Eggs != 0) %>% 
  dplyr::select(DateTime, `Nest ID`, Status, Est_LayDate:Est_HatchDate, Eggs, Chicks) %>% 
  distinct(across(`Nest ID`:Chicks), .keep_all = T) %>%
  group_by(`Nest ID`) %>% 
  arrange(`Nest ID`, DateTime) %>% 
  mutate(HatchDate = NA, .after = Est_HatchDate, 
         Est_TranspondDate5 = Est_HatchDate + 35,
         Est_TranspondDate6 = Est_HatchDate + 42,
         Est_FledgeDate = Est_HatchDate + 56) %>% 
  mutate(diffeggs = as.numeric(Eggs) - lag(as.numeric(Eggs)))

# Nests with chicks
chicks <- nests %>% 
  filter(Status == "Chicks" & Chicks != 0 | Status == "Fledged") %>% 
  #merging with failed nests to identify rows of failed nests
  left_join(data.frame("Nest ID" = failed_nests$`Nest ID`, 
                       "Failed" = failed_nests$DateTime), 
            by = c("Nest ID" = "Nest.ID")) %>% 
  group_by(`Nest ID`) %>% 
  mutate(Failed = ifelse(DateTime < Failed, "F", "A"), 
         Failed = replace_na("A")) %>% 
group_by(`Nest ID`, Failed) %>% 
  mutate(HatchDate = min(DateTime), .after = Est_HatchDate, 
         Est_TranspondDate5 = HatchDate + 35,
         Est_TranspondDate6 = HatchDate + 42,
         Est_FledgeDate = HatchDate + 56) %>% 
 dplyr::select(DateTime, `Nest ID`, Status, Est_LayDate:Est_FledgeDate, Eggs, Chicks, Failed) %>% 
  distinct(across(`Nest ID`:Chicks), .keep_all = T) %>%
  arrange(`Nest ID`, DateTime) %>% 
  mutate(diffchicks = as.numeric(Chicks) - lag(as.numeric(Chicks)), 
         diffchicks = ifelse(Status == "Fledged", NA, diffchicks),
         nrow = row_number(),
         Status = ifelse(any(Status =="Fledged"), "Fledged", Status)) %>%
  filter(nrow == 1) %>% 
  select(-c(DateTime, nrow)) %>% 
  distinct()

# Nests with fledglings
chicksfledge <- nests %>% 
  filter((Status == "Chicks" & Chicks != 0) | Status == "Fledged") %>% 
    #merging with failed nests to identify rows of failed nests
  left_join(data.frame("Nest ID" = failed_nests$`Nest ID`, 
                       "Failed" = failed_nests$DateTime), 
            by = c("Nest ID" = "Nest.ID")) %>% 
  group_by(`Nest ID`) %>% 
  mutate(Failed = ifelse(DateTime < Failed, "F", "A"), 
         Failed = replace_na("A")) %>% 
group_by(`Nest ID`, Failed) %>% 
mutate(HatchDate = min(DateTime), .after = Est_HatchDate, 
         Est_TranspondDate5 = HatchDate + 35,
         Est_TranspondDate6 = HatchDate + 42,
         Est_FledgeDate = HatchDate + 56) %>% 
  dplyr::select(DateTime, `Nest ID`, Status, Est_LayDate:Est_FledgeDate, Chicks, Failed) %>% 
  slice_tail(n = 3) %>% 
  mutate(Fledged = ifelse(Status == "Fledged", max(Chicks, na.rm = T), NA)) %>% 
  distinct() %>% 
  filter(!is.na(Fledged)) %>%
  arrange(Est_TranspondDate5) %>% 
  ungroup() %>% 
  select(-Failed)

# TOTALS
totals <- chicks %>% 
  filter(Chicks == max(Chicks)) %>%
  ungroup() %>%
  summarise(Chicks_hatched = sum(Chicks))
totals <- eggs %>% 
  filter(Eggs == max(Eggs)) %>%
  ungroup() %>%
  summarise(Total_nests = length(unique(nests$`Nest ID`)), 
            Eggs_laid = sum(Eggs),
            totals,
                Chicks_fledged = sum(chicksfledge$Fledged))
```

```{r}
# Weights

# nests where chicks fledged
xx <- chicksfledge %>% 
  select(`Nest ID`, Status)
# nests failed
xxx <- failed_nests %>% 
  filter(`Nest activity` == "FAILED")

# filtering out failed nests
weights_nests <- nests %>%
  group_by(`Nest ID`) %>% 
  #filter(row_number() < max(which("Nest Activity" == "FAILED")))
  #merging with failed nests to identify rows of failed nests
  left_join(data.frame("Nest ID" = xxx$`Nest ID`, 
                       "Failed" = xxx$DateTime), 
            by = c("Nest ID" = "Nest.ID")) %>% 
filter(is.na(Failed)) %>%  
  #group_by(`Nest ID`, Failed) %>% 
  left_join(chicks[c(1,5)], by = "Nest ID") %>% 
  select(c(1,2,4,14:19,23)) %>% 
  mutate(HatchDate = as.Date(HatchDate), 
         days_hatch = difftime(DateTime, HatchDate, units = "days"), 
         weeks_hatch = round(as.numeric(days_hatch)/7, 1)) %>% 
  filter(!is.na(`Chick 1 weight`)) %>% 
  #fledged nests
    left_join(xx, by = "Nest ID", suffix = c("2", "")) %>% 
  mutate(Status = ifelse(is.na(Status), "Active", Status), 
         Status = ifelse(Status2 == "Uplifted", "Uplifted", Status))


temp <- weights_nests %>% 
  select(-starts_with("Chick 2")) %>% 
  mutate(`Chick 1 ID` = ifelse(is.na(`Chick 1 ID`), "c1", `Chick 1 ID`)) %>% 
  rename("ID" = `Chick 1 ID`, "Fate" = `Chick 1 status`, "Weight" = `Chick 1 weight`)

weights_chick <- weights_nests %>% 
  select(-starts_with("Chick 1")) %>% 
  mutate(`Chick 2 ID` = ifelse(is.na(`Chick 2 ID`), "c2", `Chick 2 ID`)) %>% 
  rename("ID" = `Chick 2 ID`, "Fate" = `Chick 2 status`, "Weight" = `Chick 2 weight`) %>% 
  bind_rows(temp) %>% 
  arrange(`Nest ID`, ID) %>% 
  filter(!is.na(Weight)) %>% 
  mutate(days_hatch = as.numeric(days_hatch)) %>% 
  unite(col = ID, `Nest ID`, ID, sep = "-", remove = FALSE, na.rm = TRUE) %>% 
  mutate(Underweight = ifelse(Weight <= 700 & days_hatch >= 42, "Concern", "Ok"), 
         Underweight = ifelse(Weight <= 600 & days_hatch >= 42, "Intervene", Underweight)) %>% 
  select(-Status2)
clipr::write_clip(weights_chick)

ggplot(data = weights_chick, aes(x = days_hatch, y = Weight, 
                                 shape = Status, 
                                 color = `Nest ID`, 
                                 group = ID)) +
  geom_point() +
   geom_line() +
  geom_rug() +
  theme_minimal() +
  guides(color = FALSE)

```

```{r}
# add parent marking / chick marking data to df chicks
cols <- c(Adult1 = NA_real_, Adult2 = NA_real_, Chick1 = NA_real_, Chick2 = NA_real_, Adult3 = NA_real_)
birdid_chicks <- birdid %>%
  filter(`Nest ID_marking` %in% chicks$`Nest ID`) %>% 
  dplyr::select(c(`Bird ID`, `Nest ID_marking`, `Age_marking`)) %>% 
  group_by(`Nest ID_marking`, Age_marking) %>% 
  mutate(n = row_number()) %>% 
  unite(nn, Age_marking, n, sep = "") %>% 
  pivot_wider(names_from = nn, values_from = `Bird ID`) %>% 
  add_column(!!!cols[!names(cols) %in% names(.)]) %>%
  relocate(Adult2,  .after = Adult1) %>% 
  relocate(Adult3,  .after = Adult2) %>% 
  relocate(Chick2,  .after = Chick1) %>% 
  right_join(chicks, by = c("Nest ID_marking" = "Nest ID")) %>% 
  arrange(Est_TranspondDate5) %>% 
  mutate(Notes = ifelse(floor_date(Est_TranspondDate5, "weeks", week_start = 1) == tdt & 
                          is.na(Chick1) & 
                          is.na(Chick2), "Mark chicks", NA)) %>% 
  mutate(Notes = ifelse(floor_date(Est_TranspondDate6, "weeks", week_start = 1) == tdt & 
                          is.na(Chick1) & 
                          is.na(Chick2), "Mark chicks", Notes)) %>% 
  ungroup() %>% 
  #mutate_if(is.Date, ~paste0("'", .)) %>%
  #mutate(`__id` = row.names(.)) %>%
  mutate(`__id` = NA) %>%
  mutate_if(is.numeric, as.character) %>%
  mutate_if(is.Date, as.character)

# Eggs, Chicks
eggchick <- eggs %>%
  bind_rows(chicks) %>% 
  arrange(`Nest ID`, DateTime) %>% 
  left_join(birdid_chicks[1:6], by = c("Nest ID"="Nest ID_marking" )) %>% 
  left_join(nestid_coord, by = "Nest ID") %>%
  distinct()
clipr::write_clip(eggchick)


write.csv(birdid_chicks, "Chicks.csv", row.names = FALSE)
```

### Upload files to Google Drive
#### This can also be executed in KororaShiny (https://rphickcox.shinyapps.io/pohatuapp/) and 
#### C:\Users\rphic\OneDrive\Documents\GitHub\KororaShiny\PohatuApp.Rproj
```{r upload}
x <- gs4_find("Notifications")

tobind <- birdid_chicks[c(1, 15, 11, 12, 13, 16)]
temp <- read_sheet(x) %>% 
  mutate(n = 2) %>% 
  bind_rows(c(tobind, n = 1)) %>%
  group_by(`Nest ID_marking`) %>% 
  fill('__id') %>% 
  separate(Notes, ",", into = LETTERS[seq( from = 1, to = 10 )]) %>% 
  pivot_longer(cols = A:J) %>% 
  select(-name) %>% 
  distinct() %>% 
  mutate(Notes = paste0(value, collapse = ", "), 
         Notes = str_replace_all(Notes, ", NA", ""),
         Notes = str_replace_all(Notes, "NA, ", "")) %>% 
  select(-value) %>% 
  relocate(Notes, .after = 'Nest ID_marking') %>% 
  distinct() %>% 
  filter(Notes != "NA") %>% 
  mutate(nn = n()) %>% 
  filter(n == 1 | nn == 1) %>% 
  select(-c(n, nn))

write_sheet(temp, ss = x, sheet = "Notifications")
```

### Bird ID summary- formatted to NZNBBS spreadsheet 'Data BOX v.FALCON.1x'
```{r birdid}
x <- data.frame(matrix(ncol = 25, nrow = nrow(birdid)))
x[is.na(x)] <- ""

monitor <- mutate(monitor, DT = format(DateTime, "%d/%m/%Y"))
df <- data.frame(x = c("Rachel", "Ave", "Kevin", "Henry", "Kaitlyn  Leeds", "Lucy Howell"), y = c("Rachel Hickcox", "Averil Parthonnaud", "Kevin Parthonnaud", "Henry Elsom", "Kaitlyn Leeds", "Lucy Howell"), n = c(0722, 0786, 1121, 0791, 1017, 1150))

marking <- birdid %>% 
  dplyr::select(`Bird ID`, Sex:Location_marking, Tagger, `Nest ID_marking`:`Bill length_marking`) %>% 
  mutate(.before = 1, DT = format(DateTime_marking, "%d/%m/%Y")) %>% 
  left_join(monitor[c(37, 3, 16, 17)], by = c("DT" = "DT", "Nest ID_marking" = "Nest ID")) %>% 
  distinct() %>% 
  mutate(DateTime_marking = format(DateTime_marking, "%d/%m/%Y %H:%M")) %>% 
  mutate(Prefix_number = "PIT", Number = `Bird ID`, Date = DateTime_marking, 
         Date_Accuracy = "D", Banding_scheme = "NZNBBS Non-gamebird",
         L3_number = "0722", L3_Name = "Rachel Hickcox", 
         Bander_number = "",	Bander_name = Tagger, Other_name = "", Other_contact = "",
         NZNBBS_code = 1,
         Lookup_Code = "First marking",Stock_code = "",	Event_code = "first-mark-in-hand",
         Capture_code	= "1b. Captured in nest box", Wild_Captive = "Wild",
         Common_name	= "white-flippered blue penguin, kororā",	
         Scientific_name = "Eudyptula minor albosignata",	Species_code = "016", 
         Age = Age_marking, Sex_ = Sex, Region_Code =  "11. Canterbury",
         Locality_general = "1 Pōhatu/Flea Bay, Banks Peninsula",
         Locality_description = "Pōhatu/Flea Bay, Banks Peninsula", Latitude =	-43.86838,	
         Longitude = 173.00887, Easting =	1600714, Northing =	5142745, Coordinate_system =	"WGS84", 
         Locality_accuracy = 100) %>% 
  bind_cols(x[1:18]) %>% 
  mutate(Non_leg_mark_type_2	= "insertion transponder"	, Non_leg_mark_id_2 = "*",
         Status_code_1	= "alive", Condition_1 = "0. Good") %>% 
  bind_cols(x[1:2]) %>% 
  mutate(status_detail1 = Status_marking, Status_detail2 = "",
         Notes = "Permit 94750-FAU", Sent_date = format(today(), "%d/%m/%Y %H:%M"), Moratorium	= "", 
         Detail1 = "mass (excluding bag/transmitter etc.)", Units1 = "grams (g)", Data1 = Weight_marking,
         Detail2 = "bill length",	Units2 = "millimetres (mm)",	Data2 =  `Bill length_marking`, 
         Detail3 = "bill depth",	Units3 = "millimetres (mm)",	Data3 =  `Bill depth_marking`, 
         Detail4	= "nest number", Units4	= "nest number", Data4 = `Nest ID_marking`) %>% 
  bind_cols(x[1:21]) %>% 
  mutate(Project_Name	= "Pōhatu Little Penguins", Species_Group	= "Penguins") %>% 
  dplyr::select(-c(DT:`Bill length_marking`))

marking_fix <- marking %>% 
  mutate(Eggs = ifelse(is.na(Eggs), 0, Eggs), 
         Chicks = ifelse(is.na(Chicks), 0, Chicks), 
         Eggs = ifelse(Eggs == 0 & status_detail1 == "Incubating eggs", 2, Eggs), 
         Chicks = ifelse(Chicks == 0 & status_detail1 == "Guarding chicks", 2, Chicks), 
         status_detail1 = ifelse(Eggs == 2, "56. With more than one egg", status_detail1),
         status_detail1 = ifelse(Eggs == 1, "55. With egg", status_detail1),
         status_detail1 = ifelse(Chicks == 2, "58. With more than one chick", status_detail1),
         status_detail1 = ifelse(Chicks == 1, "57. With chick", status_detail1),
         status_detail1 = ifelse(status_detail1 == "Loafing", 
                                 "53. On empty nest", status_detail1)) %>%  
  mutate(Age = recode(Age, "Adult" = "A", "Chick" = "C", "Juvenile" = "J", "Unknown" ="U"), 
         Age = ifelse(is.na(Age), "U", Age), 
         Sex_ = recode(Sex_, "Female" = "FU", "Male" = "U", "Unknown" = "U"),
         Sex_ = ifelse(is.na(Sex_), "U", Sex_)) %>% 
  group_by(Data4) %>% 
  mutate(Sex_ = ifelse(Sex_ == "U" & "FU" %in% Sex_, "MU", Sex_)) %>% 
  left_join(df, by = c("Bander_name" = "x"), keep = FALSE) %>% 
  mutate(Bander_name = y, Bander_number = n) %>% 
  dplyr::select(-c(Eggs, Chicks, y, n))

marking_fix %>% 
  group_by(Age) %>% 
  summarise(Age = unique(Age), 
            Count = n())

```

```{r}
ecfate <- read_excel("nests_ecfate_18112022.xlsx")
ecfate$code <- as.factor(ecfate$code)
#ccord <- ecfate %>% filter(!is.na(Lat))
#coordinates(ccord) <- ~Lat+Long

library(leaflet)
pal <- colorFactor(c("yellow", "blue", "purple", "orange", "red"), ecfate$code)
lab <- as.character(ecfate$code)

x <- leaflet() %>% 
  #addCircles(lng = ~Long, lat = ~Lat) %>% 
  addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
           options = providerTileOptions(noWrap = TRUE), group = "World Imagery") %>%
  # addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/Mapserver/tile/{z}/{y}/{x}',
  #          options = providerTileOptions(noWrap = TRUE),group = "Labels") %>% 
  addCircleMarkers(data = ecfate, lat = ~Lat, lng = ~Long,
                   radius = 3,
                   color = ~pal(ecfate$code),
                   stroke = FALSE, fillOpacity = 1) %>%
  leaflet::addLegend(pal = pal, values = lab, opacity = 1, position = "bottomleft") %>%
  fitBounds(173.00275,-43.871,173.015,-43.866)

library(mapview)
library(htmlwidgets)
mapshot(x, file = "~/map_activefailednests.png")
saveWidget(x, selfcontained = T, file = "~/map_activefailednests.html")

resfactor <- 3
png(filename=x, res = 72*resfactor, height=640*resfactor, width=640*resfactor)
```

