---
title: "Pohatu Penguins Season Report"
author: "Rachel Hickcox"
date: "2022"
email: "rphickcox@gmail.com"
editor_options: 
  chunk_output_type: console
---

### Load packages
```{r pkg, eval=TRUE, message=FALSE, warning=FALSE, cache=FALSE}
pkgs <- c("knitr", "kableExtra", "broom", 
          "readxl", "flextable", "terra", "googlesheets4", "googledrive", 
          "lubridate", "tidyverse", "openxlsx")
new.packages <- pkgs[!(pkgs %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
invisible(lapply(pkgs, library, character.only = TRUE))
rm(list = c("pkgs", "new.packages"))
options(scipen = 999)
```


### Reading in cleaned yearly summary of breeding
#### These Excel sheets were generated from M1_DataProcessing.Rmd 
#### and cleaned manually in Excel. It contains one row per nest ID for a certain season
```{r cleanedsum}
cols <-  c("numeric", rep("text", 5), rep("numeric", 3), rep("text", 6),
           rep("date", 6), "text", "numeric")

breeding <- lapply(list.files("./../ALL_DATA/Data", pattern = "finalsummary_edited.xlsm", full.names = TRUE,
                              recursive = TRUE, include.dirs = TRUE), 
                   read_excel, col_types = cols)
#names(breeding[[1]]) == names(breeding[[2]])
```


### Summary tables
```{r}
#x <- breeding[[2]]

summary_nests <- function(x){
  # Adults marked
  df_br <- x %>%
    pivot_longer(names_to = "Name", values_to = "BirdID", cols = c("Adult1ID", "Adult2ID")) %>%
    filter(BirdID != "UM")
  
  # Chicks marked
  df_ch <- x %>%
    pivot_longer(names_to = "Name", values_to = "BirdID", cols = c("Chick1ID", "Chick2ID")) %>%
    filter(BirdID != "UM")
  
  df <- x %>%
    filter(rowSums(is.na(.)) < ncol(.)) %>%
    summarise(
      NestYear = unique(NestYear),
      Nests = nrow(x),
      Nestboxes = length(unique(NestID)),
      TwoClutch = sum(grepl("[._]", SeasonID)),
      NestsFailed = length(Status[Status == "Failed"]),
      NestsUplifted = length(Status[Status == "Uplifted"]),
      NestsFledged = length(Status[Status == "Fledged"]),
      MarkedAdults = length(c(Adult1ID[Adult1ID != "UM"], Adult2ID[Adult2ID != "UM"])),
      MarkedChicks = length(c(Chick1ID[!is.na(Chick1ID) & Chick1ID != "UM"], 
                              Chick2ID[!is.na(Chick2ID) & Chick2ID != "UM"])),
      Laid = sum(NLaid),
      Hatched = sum(NHatched),
      Fledged = sum(NFledged),
      OneLaid = length(NLaid[NLaid == 1]),
      TwoLaid = Laid - OneLaid,
      ZeroHatch = length(NHatched[NHatched == 0]),
      OneHatch = length(NHatched[NHatched == 1]),
      TwoHatch = Hatched - ZeroHatch - OneHatch,
      Fledged_Assisted = length(c(EC1Fate[EC1Fate %in% "CFledgedAssisted"], EC2Fate[EC2Fate %in% "CFledgedAssisted"])),
      Fledged_Natural = length(c(EC1Fate[EC1Fate %in% "CFledged"], EC2Fate[EC2Fate %in% "CFledged"])),
      SF = length(c(EC1Intervention[EC1Intervention %in% c("SFR", "SF", "SFHR", "SFRH")], 
                    EC2Intervention[EC2Intervention %in% c("SFR", "SF", "SFHR", "SFRH")])),
      #fates = table(c(EC1Fate, EC2Fate)),
      Percent_EggsHatched_perLaid = round((Hatched/Laid)*100, 2), # percent eggs laid that hatched
      Percent_ChicksFledged_perHatched = round((Fledged/Hatched)*100, 2), # percent chicks fledged that hatched
      Percent_ChicksFledged_Natural_perHatched = round((Fledged_Natural/Hatched)*100, 2), # percent chicks fledged that hatched NO REHAB
      Percent_ChicksFledged_perLaid = round((Fledged/Laid)*100, 2), # percent chicks fledged that were laid
      HatchingSuccess_perPair = round(Hatched/Nests, 2), # fledged per breeding pair (i.e., nest)
      FledgingSuccess_perPair = round(Fledged/Nests, 2), # fledged per breeding pair (i.e., nest)
      FledgingSuccess_perPair_Natural = round((Fledged-Fledged_Assisted)/Nests, 2), # fledged per breeding pair NO REHAB
      LayDate_min = as.Date(min(Est_LayDate, na.rm = TRUE)),
      LayDate_mean = as.Date(mean(Est_LayDate, na.rm = TRUE)),
      LayDate_max = as.Date(max(Est_LayDate, na.rm = TRUE)),
      HatchDate_min = as.Date(min(HatchDate, na.rm = TRUE)),
      HatchDate_mean = as.Date(mean(HatchDate, na.rm = TRUE)),
      HatchDate_max = as.Date(max(HatchDate, na.rm = TRUE)),
      FledgeDate_min = as.Date(min(FledgeDate, na.rm = TRUE)),
      FledgeDate_mean = as.Date(mean(FledgeDate, na.rm = TRUE)),
      FledgeDate_max = as.Date(max(FledgeDate, na.rm = TRUE)), 
      Adults_marked = nrow(df_br), 
      Chicks_marked = nrow(df_ch)
    )
  
  return(df)
}


summary_list <- as.data.frame(t(bind_rows(lapply(breeding, summary_nests)))) %>%
  mutate(Variable = row.names(.), .before = 1) 
names(summary_list) <- c("Variable", summary_list[1,2:length(summary_list)])
summary_list <- summary_list[-1,]
rownames(summary_list) <- NULL

```

# Save
```{r}
write.csv(summary_list, "./../ALL_DATA/Data/2025-2026/SeasonsSummaryReport.csv", row.names = FALSE)
```

# Plots
```{r}
library(patchwork)

# -- Assumes df_summary has one row per NestYear from your summarise() output --

# Colour palette
col_laid    <- "#3266ad"
col_hatched <- "#1d9e75"
col_fledged <- "#d85a30"
col_flednat <- "#d4537e"
col_nests   <- "#7f77dd"
col_twocl   <- "#ef9f27"

base_theme <- theme_classic(base_size = 11) +
  theme(axis.title = element_text(size = 10),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"))

df_summary <- summary_list %>%
  pivot_longer(-Variable, names_to = "NestYear", values_to = "value") %>%
  mutate(NestYear = as.integer(NestYear),
    value    = as.numeric(trimws(value))) %>%
  #pivot_wider(names_from = Variable, values_from = value)
filter(Variable %in% c("Nests", "Nestboxes", "Laid", "Hatched", "Fledged", 
                       "Percent_EggsHatched_perLaid",   
                       "Percent_ChicksFledged_perHatched",
                       "Percent_ChicksFledged_perLaid", 
                       "HatchingSuccess_perPair",
                       "FledgingSuccess_perPair"))


pct_vars  <- c("Percent_EggsHatched_perLaid",
               "Percent_ChicksFledged_perHatched",
               "Percent_ChicksFledged_perLaid")
pair_vars <- c("HatchingSuccess_perPair","FledgingSuccess_perPair")

# Bar chart of success perentages
p1 <-
  df_summary %>%
  filter(Variable %in% pct_vars) %>%
  mutate(Variable = factor(Variable, levels = pct_vars),
         NestYear = factor(NestYear),
         x_pos = as.numeric(Variable) + 
                   (as.numeric(NestYear) - 2.5) * 0.2) %>%
  ggplot(aes(x_pos, value, fill = NestYear)) +
  geom_col(width = 0.2) +
  geom_line(aes(group = Variable), colour = "orange", linewidth = 1) +
  geom_text(aes(label = round(value, 1)), colour = "white",
            vjust = 2, size = 3, fontface = "bold") +
  scale_fill_viridis_d(option = "mako", begin = 0.1, end = 0.8) +
  scale_colour_viridis_d(option = "mako", begin = 0.1, end = 0.8) +
  scale_x_continuous(breaks = 1:3,
                     labels = c("Hatching success \n(Eggs hatched/Eggs laid)",
                                "Fledging success \n(Chicks fledged/Eggs hatched)",
                                "Breeding success \n(Chicks fledged/Eggs laid)")) +
scale_y_continuous(limits = c(0, 100), expand = FALSE) +
  labs(x = NULL, y = "Percent", fill = NULL, colour = NULL) +
  theme_classic(base_size = 12) +
  theme(legend.position = "bottom")

p2 <- 
  df_summary %>%
  filter(Variable %in% c("Laid", "Hatched", "Fledged")) %>%
  mutate(Variable = factor(Variable, levels = c("Laid", "Hatched", "Fledged")),
         NestYear = factor(NestYear),
         x_pos = as.numeric(Variable) + 
                   (as.numeric(NestYear) - 2.5) * 0.2) %>%
  ggplot(aes(x_pos, value, fill = NestYear)) +
  geom_col(width = 0.2) +
  geom_line(aes(group = Variable), colour = "orange", linewidth = 1) +
  geom_text(aes(label = round(value, 1)), colour = "white",
            vjust = 2, size = 3, fontface = "bold") +
  scale_fill_viridis_d(option = "mako", begin = 0.1, end = 0.8) +
  scale_x_continuous(breaks = 1:3,
                     labels = c("Eggs laid", "Eggs hatched", "Chicks fledged")) +
  scale_y_continuous(limits = c(0, 400), expand = FALSE) +
labs(x = NULL, y = "Count", fill = NULL) +
  theme_classic(base_size = 12) +
  theme(legend.position = "none")

# Combine 
ggsave(p2/p1, filename = "./../ALL_DATA/Data/BreedingSuccess_plot_allyears.png",
       width = 8, height = 5, dpi = 300)


# Secondary axis breeding success

scale_factor <- 50

ggplot() +
  geom_line(data = filter(df_summary, Variable %in% pct_vars),
            aes(NestYear, value, colour = Variable), linewidth = 0.8) +
  scale_y_continuous(
    name = "Percent (%)",
    sec.axis = sec_axis(~ . / scale_factor, name = "Success per pair")
  ) +
  scale_x_continuous(breaks = unique(df_summary$NestYear)) +
  theme_classic(base_size = 11)




```

