---
title: "Pohatu Penguins Graphing of Kobo App Survey results"
author: "Rachel Hickcox"
date: "2025"
email: "rphickcox@gmail.com"
editor_options: 
  chunk_output_type: console
---

# This script grooms and graphs data from Kobo Toolbox forms, which record the number of penguins and rafts observed on tour

### Load packages
```{r pkg, eval=TRUE, message=FALSE, warning=FALSE, cache=FALSE}
pkgs <- c("ggplot2", "readxl", "flextable", "terra", "googlesheets4", "googledrive", 
          "lubridate", "tidyverse", "openxlsx")
new.packages <- pkgs[!(pkgs %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
invisible(lapply(pkgs, library, character.only = TRUE))
rm(list = c("pkgs", "new.packages"))
options(scipen = 999)
```

### Read in data
```{r}
kobo_1 <- read.xlsx(paste0("./../ALL_DATA/Data/Tour counts and nest checks/", "2024 JuneSept_Penguin_Counts_During_Tour.xlsx"), )
kobo_2024 <- read.xlsx(paste0("./../ALL_DATA/Data/Tour counts and nest checks/", "2024-2025 Penguin_Counts_During_Tour.xlsx"))
kobo_2025 <- read.xlsx(paste0("./../ALL_DATA/Data/Tour counts and nest checks/", "2025-2026 Penguin_Counts_During_Tour.xlsx"))

```

## Combine tables
```{r}
kobo_2025_f <- kobo_2025 %>% select(names(kobo_2024))
kobo <- rbind(kobo_1, kobo_2024, kobo_2025_f) %>%
  mutate(date = as.Date(date, origin = "1899-12-30"), 
         time = format(as.POSIXct(as.numeric(time) * 86400, origin = "1970-01-01", tz = "UTC"), "%H:%M")) %>%
  arrange(date, time) %>%
  select(-c(tour_other, guide_other, starts_with("_")))

kobo_water <- kobo %>%
  select(c(date:clients, main_hide_water:kayak_water, full_moon)) %>%
  mutate(across(main_hide_water:kayak_water, ~ str_extract(.x, "^\\d{1,2}")), 
         across(main_hide_water:kayak_water, ~ str_replace_all(., "51", "5")), 
         across(main_hide_water:kayak_water, ~ str_replace_all(., "15", "1")), 
         across(main_hide_water:kayak_water, ~ as.numeric(.))) %>%
  pivot_longer(cols = main_hide_water:kayak_water, names_to = "hide", values_to = "count") %>%
  mutate(hide = as.factor(hide)) %>% 
  group_by(date, tour, hide) %>%
  filter(!is.na(count), !hide %in% c("pine_tree_hide_water", "kakak_water"), tour == "evening") %>%
  mutate(hide = str_replace_all(hide, "(\\w+)_hide_water", "\\1 hide"), 
         hide = str_to_sentence(hide), 
         full_moon2 = ifelse(full_moon != "yes", "No", "Yes"), 
         year = year(date), 
         penguin_year = factor(ifelse(month(date) >= 7, year(date), year(date) - 1)),
         yday_shift = (yday(date) - yday(as.Date(paste0(ifelse(month(date) >= 7, 
                                                              year(date), 
                                                              year(date) - 1), "-07-01")))) %% 365) %>%
filter(penguin_year != "2023")

# Gaps of >5 days are not connected with a smooth line
kobo_water2 <- kobo_water %>%
  arrange(date) %>%
  group_by(penguin_year, hide) %>%
  mutate(gap = c(0, diff(yday_shift)) > 28,        # flag gaps > 5 days
         segment = cumsum(gap)) %>%                  # new segment after each gap
  ungroup()


# Plot
ggplot(kobo_water2, aes(x = yday_shift, y = count, colour = penguin_year,
                        shape = as.factor(tolower(full_moon2)))) +
  geom_point(aes(fill = penguin_year), size = 2) + 
  scale_shape_manual(values = c(1, 16), labels = c("Other", "Full Moon"), name = "Moon Phase") +
  scale_colour_manual(values = c("steelblue", "darkorange", "forestgreen"),
                      labels = c("2024–25", "2025–26", "2026–27"), name = "Year") +
  scale_fill_manual(values = c("steelblue", "darkorange", "forestgreen"),
                    labels = c("2024–25", "2025–26", "2026–27"), name = "Year") +
  new_scale_colour() +
geom_smooth(aes(group = interaction(penguin_year, hide, segment), colour = penguin_year),
           # method = "gam", formula = y ~ s(x, bs = "cs"), se = TRUE) +
            method = "loess", span = 0.5, se = TRUE) +
scale_colour_manual(values = c("steelblue", "darkorange", "forestgreen"),
                      labels = c("2024–25", "2025–26", "2026–27"), name = "Year") +
  facet_wrap(~ hide) +
  labs(x = "Date", y = "Number of penguins on the water") +
  theme_classic() +
scale_x_continuous(expand = c(0, 0),
                   breaks = c(0, 31, 62, 92, 123, 153, 183, 214, 243, 274, 304, 335),
                   labels = c("Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun")) +
scale_y_continuous(expand = c(0, 0), breaks = c(0, 5, 10, seq(20, 100, by = 20))) +
  coord_cartesian(ylim = c(0, 100)) +
  theme(panel.grid.major.x = element_line(color = "lightgray", size = 0.1),
        panel.border = element_rect(colour = "black", fill = "transparent"), 
        legend.position = "bottom")

ggsave("./../ALL_DATA/Data/Tour counts and nest checks/Birdsonwater_yearly_perhide.png", height = 7)
```

