---
output: html_document
editor_options: 
  chunk_output_type: console
---
# ---
# title: "Pohatu Penguins GPS/TDR Data Process File"
# author: "Rachel Hickcox"
# date: "2023"
# email: "rphickcox@gmail.com"
# ---


### Load packages 
```{r}
pkgs <- c("tidyr", "plyr", "terra", "sf", "ggplot2",
          "lubridate", "dplyr", "ggspatial", "stringr",
          "spThin", "diveMove", "adehabitatHR", "data.table", "reshape2", #"tlocoh", 
          "knitr", "flextable", "here", "argosfilter", "basemaps", "osmdata", "ggmap")
invisible(lapply(pkgs, library, character.only = TRUE))
#load_pkgs(pkgs)
options(scipen = 999)
```

### Loading map files
```{r}
local.tz <- "Pacific/Auckland"
nz_water <- st_read("../ALL_DATA/Mapping/nz_polygon_nztm2000_water75.shp")

#si <- st_read("../ALL_DATA/Mapping/NZ_polygon_NZTM2000_fixed.shp") 
#siec_line <- st_read("../ALL_DATA/Mapping/Southisland_line.shp")
nz <- st_read("../ALL_DATA/Mapping/NZ_fullcountry_NZTM2000.shp")
bp <- st_read("../ALL_DATA/Mapping/bankspeninsula_region_marine.shp")
nz_marine <- st_read("../ALL_DATA/Mapping/nz_polygon_nztm2000_water75.shp")

bathymetry <- rast("../ALL_DATA/Mapping/bathymetry_formapping.tif")

nzgd2000 <- 2193

wgs84 <- 4326  # EPSG code 4326 (WGS84)

```

### Setup
```{r}
# These change depending on the folder
nestcoords <- read.csv("C:/Users/rphic/OneDrive/Documents/GitHub/ALL_DATA/Data/2024-2025/Nest ID - 2024.csv")
temp <- dplyr::filter(nestcoords, !is.na("Lat"))
bsite <- "Pohatu" 
xx <- data.frame()
tracks <- data.frame()

folder_in <- "C:/Users/rphic/OneDrive/Documents/Pohatu_data/Breeding_2024"
folder_out <- "C:/Users/rphic/OneDrive/Documents/Pohatu_data/Breeding_2024_Kaitlin_clean"
files_list_in <- list.files(path = folder_in, pattern = "*.csv", full.names = FALSE)
files_list_out <- list.files(path = folder_out, pattern = "*.csv", full.names = FALSE)
#files_list <- list.files(path = folder_out, pattern = "*.csv", full.names = FALSE)

# Df of file names from wd used to assign microchip number/sex,year, season assigned to variables
files_fix <- files_list_in[!files_list_in %in% files_list_out]

files_read <- files_list_in[files_list_in %in% files_list_out]
files_read <- files_list_out
```

### Toread function
```{r}
toread <- function(toread, folder_in, folder_out){
  nam <- unlist(strsplit(toread, "_"))
  year <- unlist(strsplit(nam[[4]], "[.]"))
  year <- paste(str_sub(year[[1]], 1, 7 ))
  season <- paste(nam[[3]])
  season <- toupper(season)
  nb <- paste(nam[[1]])
  nam <- paste(nam[[2]])
  nam <- toupper(nam)
  point_bathy <- fread(paste(folder_out, toread, sep = "/"),  
                       data.table = FALSE, sep = ",", fill = TRUE)
  point_bathy$season <- season
  point_bathy$year <- year
  tracks <- point_bathy
  
  # tripno <- max(point_bathy$trips)
  # tstart <- min(point_bathy$timestamp_NZDT, na.rm = TRUE)
  # tend <- max(point_bathy$timestamp_NZDT, na.rm = TRUE)
  # n <- nrow(point_bathy)
  # duration_h <- as.double(difftime(point_bathy[nrow(point_bathy), 15], point_bathy[1, 15]), 
  #                         units = "hours") # From first dive to last dive event
  # dis_travelkm <- sum(point_bathy$distance.m, na.rm = TRUE)/1000
  # 
  # meandepth <- mean(point_bathy$depth, na.rm = TRUE)
  # maxdepth <- max(point_bathy$depth, na.rm = TRUE)
  # dist_nest_max <- max(point_bathy$dist_nest, na.rm = TRUE)/1000
  # 
  # xxx <- data.frame(nam, nb, tripno, n, tstart, tend, duration_h, dis_travelkm, 
  #                   meandepth, maxdepth, dist_nest_max) %>%
  #   mutate(meandepth = na_if(meandepth, "NaN"), maxdepth = na_if(maxdepth, "-Inf"))
  # tracks <- list(xxx, point_bathy)
  return(tracks)
}
```
### To fix function
```{r}
tofix <- function(toread, folder_in, folder_out){
  nam <- unlist(strsplit(toread, "_"))
  year <- unlist(strsplit(nam[[4]], "[.]"))
  year <- paste(str_sub(year[[1]], 1, 7 ))
  season <- paste(nam[[3]])
  season <- toupper(season)
  nb <- paste(nam[[1]])
  nam <- paste(nam[[2]])
  nam <- toupper(nam)
  cc <- fread(paste(folder_in, toread, sep = "/"),  
              data.table = FALSE, sep = ",", fill = TRUE)
  cc <- cc %>%
    dplyr::select(1:15)
  names(cc) <- c("ID", "timestamp", "x", "y", "z", "activity", "depth", "temperature", 
                 "lat", "lon", "height_above_msl", "groundspeed", "satellite_count", 
                 "hdop", "max_signal") # Adds header with correct names
  cc <- filter(cc, (!is.na(cc$lat) | !is.na(cc$depth))) # Keeps rows with a coordinate or a depth
  
  # Adding NZDT timestamp column to cc 
  cc$timestamp_UTC <- parse_date_time(cc$timestamp, 
                                      orders = c("Ymd HMS", "dmY HMS"),
                                      tz = "UTC")
  cc$timestamp_NZDT <- with_tz(cc$timestamp_UTC, "Pacific/Auckland")
  cc$ID <- nam
  
  # Removing TDR data; coordinates only 
  cccord <- filter(cc, (!is.na(cc$lat) & !is.na(cc$lon))) # Removes rows lat and lon == NA
  cccord <- cccord %>%
    filter(lon != 0) %>%  # Removes rows lon == 0
    distinct(lon, lat, .keep_all = TRUE) #Removes rows duplicated lon values
  
  # Filtering cccord to remove points with a groundspeed > 7.4 and satellite count <4 (marine DF created)
  marine <- cccord %>% 
    filter(satellite_count >= 3 | is.na(satellite_count)) %>%
    filter(timestamp != "29/10/2022 23:21:08.000")
  marine <- filter(marine, marine$groundspeed <= 12 | is.na(marine$groundspeed))
  #marine <- filter(marine, marine$groundspeed <= 7.4 | is.na(marine$groundspeed))
  
  # Duplicating coordinates in marine so they are retained after setting coordinates
  latlon <- data.frame(marine$lon,marine$lat) # Dataframe with just coordinates
  names(latlon) <- c("lon_1", "lat_1")
  marine <- cbind(marine, latlon) 
  
  # Making marine df a SpatialPointsDataFrame
  marine <- st_as_sf(marine, coords = c("lon","lat"), crs = st_crs(wgs84)) # lat long not Northing Easting 
  marine <- st_transform(marine, 2193)
  
  # Subsetting points to include only those that are within the ocean, saving
  # (some GPS devices were not turned off, so there are land points) 
  # Using the nz_marine polygon layer as a mask
  marine <- marine[nz_marine, ]
  #plot(marine)
  
  # Calculating the number of trips and creating a df with total trip numbers for each individual
  marine_df <- data.frame(marine)
  marine_df <- marine_df[order(marine_df$timestamp_NZDT),] 
  marine_df$interval <- c(NA, diff(marine_df$timestamp_NZDT))
  marine_df$trips <- cumsum(c(TRUE, marine_df$interval[-1] > 14400)) # 5 hours
  #marine_df$trips <- cumsum(c(TRUE, marine_df$interval[-1] > 21600)) # 6 hours
  marine_df$optional <- NULL
  
  ################### ORIGINAL GPS + INTER GPS ###################################
  # Creating ltraj (adehabitatLT)
  # Calculating distance between points, net squared displacement (R2n), abs. angle, relative angle
  trajectory <- as.ltraj(xy = cbind(marine_df$lon, marine_df$lat),
                         date = marine_df$timestamp_NZDT,
                         id = marine_df$ID,
                         burst = marine_df$trips,
                         typeII = TRUE)
  
  # Regularisation of movement trajectory to every 1 minutes  
  # Settings on GPS to take location every 60 sec
  refda <- round_date(min(marine_df$timestamp_NZDT, na.rm = TRUE), unit = "minute") # The reference time stamp
  traj_na <- setNA(trajectory, refda, 1, units = "min") # Adds NA values every 60 sec
  traj_eq <- sett0(traj_na, refda, 1, units = "min")  # Rounds each interval to nearest min
  traj_int <- redisltraj(na.omit(traj_eq), 60, type = "time") # Linearly interpolates points every 1 min
  #X11(type = "Xlib")
  #trajdyn(traj_red)
  df_traj <- ld(traj_int) # ltraj to dataframe  
  df_traj <- df_traj[!is.na(df_traj$x), ]
  df_traj <- df_traj[!is.na(df_traj$y), ]
  df_traj$burst <- as.numeric(as.character(df_traj$burst))
  df_traj <- df_traj[order(df_traj$burst), ] 
  traj_red <- dl(df_traj) # Dataframe to ltraj  
  #plot(traj_red)
  #plot(traj_red[1])
  
  ###  TRYING OUT SECOND INTERPOLATIONS FOR DIVES
  # Regularisation of movement trajectory to every 1 minutes  
  # Settings on GPS to take location every 60 sec
  refda <- round_date(min(marine_df$timestamp_NZDT, na.rm = TRUE), unit = "sec") # The reference time stamp
  traj_na <- setNA(trajectory, refda, 1, units = "sec") # Adds NA values every 60 sec
  traj_eq <- sett0(traj_na, refda, 1, units = "sec")  # Rounds each interval to nearest min
  traj_int <- redisltraj(na.omit(traj_eq), 1, type = "time") # Linearly interpolates points every 1 min
  #X11(type = "Xlib")
  #trajdyn(traj_red)
  df_traj <- ld(traj_int) # ltraj to dataframe  
  df_traj <- df_traj[!is.na(df_traj$x), ]
  df_traj <- df_traj[!is.na(df_traj$y), ]
  df_traj$burst <- as.numeric(as.character(df_traj$burst))
  df_traj <- df_traj[order(df_traj$burst), ] 
  traj_red <- dl(df_traj) # Dataframe to ltraj  
  #plot(traj_red)
  #plot(traj_red[1])
  
  divefull_join <- cc %>%
    left_join(df_traj, by = c("timestamp_UTC" = "date")) %>%
    mutate(depth = ifelse(depth < 1, 0, depth))
  
  library(plotly)
  # Create the 3D scatter plot
  plot_ly(data = divefull_join[divefull_join$burst == 1,], x = ~x.y, y = ~y.y, z = ~-depth,
          type = "scatter3d", 
          mode = "lines+markers", 
          marker = list(size = .5),  # Small dots
          line = list(width = 2),   # Line width
          text = timestamp,         # Hover information: timestamp
          hoverinfo = "text"        # Show timestamp on hover
  ) %>%
    layout(
      title = "3D Plot with Small Dots and Lines Based on Timestamp",
      scene = list(
        xaxis = list(title = "X Axis"),
        yaxis = list(title = "Y Axis"),
        zaxis = list(title = "Z Axis")
      )
    )
  
  
  
  ###
  shpoint_dive <- marine_df
  coordinates(shpoint_dive) <- ~lon + lat
  crs(shpoint_dive) <- nztm
  bathy_extract <- raster::extract(bathymetry,
                                   shpoint_dive,
                                   fun = max,
                                   na.rm = TRUE)
  
  # Distance to breeding area, distance to land
  dist_land <- gDistance(nz, 
                         shpoint_dive, 
                         byid = TRUE)
  bsite_coord <- nestcoords[nestcoords$Nest.ID == nb,]
  bsite_coord <- SpatialPoints(bsite_coord[c(3, 2)], CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
  bsite_coord <- spTransform(bsite_coord, nztm)
  
  dist_nest <- gDistance(bsite_coord, 
                         shpoint_dive, 
                         byid = TRUE)
  point_bathy <- cbind(marine_df, bathy_extract, dist_land, dist_nest)
  names(point_bathy)[23:24] <- c("dist_land", "dist_nest")
  
  # Recalculating dist/angle/step length for interpolated dive data 
  point_traj <- as.ltraj(xy = cbind(point_bathy$lat, point_bathy$lon),
                         date = point_bathy$timestamp_NZDT,
                         id = point_bathy$ID,
                         burst = point_bathy$trips,
                         typeII = TRUE, 
                         proj4string = nztm)
  point_trajdf <- ld(point_traj) # ltraj to dataframe  
  point_bathy <- data.frame(point_bathy, point_trajdf$dist)
  names(point_bathy)[25] <-  "distance.m"
  point_bathy$nestbox <- nb
  write.csv(point_bathy, paste0(folder_out, "/", nb, "_", tolower(nam), "_", tolower(season), "_", year, ".csv"), row.names = FALSE)
  
  # Stats
  xxxx <- data.frame()
  for(i in 1:max(point_bathy$trips)){
    tt <- point_bathy[point_bathy$trips == i,]
    tripno <- max(tt$trips)
    tstart <- min(tt$timestamp_NZDT, na.rm = TRUE)
    tend <- max(tt$timestamp_NZDT, na.rm = TRUE)
    n <- nrow(tt)
    duration_h <- as.double(difftime(tt[nrow(tt), 15], tt[1, 15]), 
                            units = "hours") # From first dive to last dive event
    dis_travelkm <- sum(tt$distance.m, na.rm = TRUE)/1000
    
    meandepth <- mean(tt$depth, na.rm = TRUE)
    maxdepth <- max(tt$depth, na.rm = TRUE)
    dist_nest_max <- max(tt$dist_nest, na.rm = TRUE)/1000
    
    xxx <- data.frame(nam, nb, tripno, n, tstart, tend, duration_h, dis_travelkm, 
                      meandepth, maxdepth, dist_nest_max) %>%
      mutate(meandepth = na_if(meandepth, "NaN"), maxdepth = na_if(maxdepth, "-Inf"))
    xxxx <- bind_rows(xxxx, xxx)
  }
  tracks <- list(xxxx, point_bathy)
  return(tracks)
}

# Points to line function
# https://rpubs.com/walkerke/points_to_line
points_to_line <- function(data, long, lat, id_field = NULL, sort_field = NULL) {
  # Convert to SpatialPointsDataFrame
  coordinates(data) <- c(long, lat)
  
  # Split into a list by ID field
  paths <- sp::split(data, data[[id_field]])
  sp_lines <- SpatialLines(list(Lines(list(Line(paths[[1]])), names(paths[1]))))
  
  for (p in 2:length(paths)) {
    id <- names(paths[p])
    l <- SpatialLines(list(Lines(list(Line(paths[[p]])), id)))
    sp_lines <- spRbind(sp_lines, l)
  }
  
  return(sp_lines)
}
```

### Applying functions
```{r}

tracks <- lapply(FUN = toread, files_read,
                 folder_in = folder_out, folder_out = folder_out)

tracks_fix <- lapply(FUN = tofix, files_fix,
                     folder_in = folder_in, folder_out = folder_out)
```

### Mapping
```{r}
tt <- tracks
tracks <- bind_rows(tracks) %>%
  filter(!is.na(date)) %>%
  arrange(id, date) %>%
  mutate(ID = paste(tolower(id), V21, tolower(season), year, sep = "_"))

tracks <- tracks %>%
  #  filter(id != "M956000015723139") %>%
  filter(id != "M956000015813216")

# Convert the dataframe to a sf object (Points)
sf_points <- st_as_sf(tracks, coords = c("X", "Y"), crs = 2193)
sf_lines <- sf_points %>%
  st_as_sf(coords = c("x", "y"), crs = 2193) %>%
  group_by(ID, season, year) %>%
  dplyr::summarize(do_union=FALSE) %>%  # do_union=FALSE doesn't work as well
  st_cast("LINESTRING") 

maplines <- sf_lines %>% st_transform(crs = 4326)

# Colors
maplines$Lines <- as.factor(unique(tracks$ID))
maplines$ID <- as.factor(unique(tracks$ID))
colours2 <- leaflet::colorFactor(
  palette = "Set3", 
  domain = maplines$Lines)

labelFormat <- function(type, cuts, p){ 
  n = length(cuts) 	
  cuts[n] = "Trip end" 	
  for(i in 2:(n-1)){cuts[i] = ""} 
  cuts[1] = "Trip start" 	
  paste0(cuts[-n], cuts[-1])}



leaflet() %>% 
  #addCircles(lng = ~Long, lat = ~Lat) %>%
  addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
           options = providerTileOptions(noWrap = TRUE), group = "World Imagery") %>%
  addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/Mapserver/tile/{z}/{y}/{x}',
           options = providerTileOptions(noWrap = TRUE),group = "Labels") %>%
  addPolylines(data = maplines, 
               group = "Lines", 
               color = ~colours2(maplines$ID), 
               opacity = 1, 
               weight = 1.25) %>% 
  # addCircleMarkers(data = tomap, lat = ~lat_1, lng = ~lon_1, 
  #                  group = ~Points,
  #                  radius = 1, popup = paste("Time: ", tomap$timestamp_NZDT, "<br>",
  #                                            "Trip: ", tomap$trips, "<br>",
  #                                            "Depth: ", round(tomap$depth, 2), "m", "<br>",
  #                                            "Bathymetry: ", round(tomap$bathy_extract, 2), "m", "<br>",
  #                                            "Distance from nest: ", round(tomap$dist_nest, 2)/1000, "km", "<br>"),
  #                  color = ~colours2(tomap$Points), #(tomap$timestamp_NZDT),
  #                  stroke = FALSE, fillOpacity = 1) %>% 
  #addLayersControl(#baseGroups = c("Points", "Lines"),
  #overlayGroups = c(unique(tomap$Points), unique(maplines$Lines)),
# overlayGroups = maplines$Lines,
#               options = layersControlOptions(collapsed = FALSE)) %>%
leaflet::addLegend(pal = colours2,
                   values = maplines$ID,
                   position = 'bottomleft',
                   title = 'Bird ID_Nestbox_Stage_Season', 
                   group = 'Lines') %>%
  # leaflet::addLayersControl(
  # overlayGroups = "Lines",
  # options = layersControlOptions(collapsed = FALSE)) %>% 
  leaflet::addScaleBar("bottomleft")

```

# Seasonal
```{r}
# Assuming maplines has a column called 'season'
leaflet() %>%
  # Add world imagery tile layer
  addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', 
           options = providerTileOptions(noWrap = TRUE), 
           group = "World Imagery") %>%
  # Add labels tile layer
  addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/Mapserver/tile/{z}/{y}/{x}', 
           options = providerTileOptions(noWrap = TRUE), 
           group = "Labels") %>%
  # Add polylines for each unique season, dynamically grouping them by 'season'
  addPolylines(data = maplines, 
               group = ~as.character(season),  # Use the 'season' column as the group identifier
               color = ~colours2(maplines$ID), 
               opacity = 1, 
               weight = 2) %>%
# Add a legend to the map
  leaflet::addLegend(pal = colours2,
                     values = maplines$ID,
                     position = 'bottomright',
                     title = 'Bird ID_Nestbox_Stage_Season', 
                     group = 'Lines') %>%
  # Add layer control for toggling visibility of the seasons
  leaflet::addLayersControl(
    overlayGroups = unique(as.character(maplines$season)),  # Dynamically create the list of overlay groups based on the 'season' column
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  # Add scale bar to the map
  leaflet::addScaleBar(position = "bottomleft")
```


```{r}
tt <- tracks
tracks <- bind_rows(tracks) %>%
  filter(!is.na(date)) %>%
  arrange(id, date)

# Convert the dataframe to a sf object (Points)
sf_points <- st_as_sf(tracks, coords = c("X", "Y"), crs = 2193)
sf_lines <- sf_points %>%
  st_as_sf(coords = c("x", "y"), crs = 2193) %>%
  group_by(id, year, season) %>%
  dplyr::summarize(do_union=FALSE) %>%  # do_union=FALSE doesn't work as well
  st_cast("LINESTRING") %>%
  mutate(season = factor(season, levels = c("PREBREEDING", "INCUBATION", "GUARD", "POSTGUARD")))

maplines <- sf_lines %>% st_transform(crs = 3857) 

# Bounding box 
set_defaults(map_service = "esri", map_type = "world_ocean_base")
sa_bb1 <- st_bbox(sf_lines)
sa_bb <- st_polygon(list(rbind(c(sa_bb1$xmin, sa_bb1$ymin),
                               c(sa_bb1$xmax, sa_bb1$ymin),
                               c(sa_bb1$xmax, sa_bb1$ymax),
                               c(sa_bb1$xmin, sa_bb1$ymax),
                               c(sa_bb1$xmin, sa_bb1$ymin))))
sa_bb <- st_sf(geometry = st_sfc(sa_bb), crs = 2193)
sa_bb <- st_buffer(sa_bb, 3000)
sa_bb <- st_transform(sa_bb, crs = 3857)
sa_bb <- st_bbox(sa_bb)
names(sa_bb) <- c("left", "bottom", "right", "top")

pal <- leaflet::colorFactor(palette = 'Set1', domain = tracks$ID)
pal <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# Plot
pplot <- 
  ggplot() + 
  basemap_gglayer(sa_bb) +
  scale_fill_identity() + 
  coord_sf(expand = FALSE) +
  geom_sf(
    dat = maplines, 
    mapping = aes(geometry = geometry,
                  color = id)) +
  facet_wrap(~season, nrow = 3) +
  labs(x = "Longitude", y = "Latitude") +
  #scale_color_viridis_d() + 
  scale_color_manual(values = pal) +
  #guides(color = guide_legend(title = "Bird ID", theme(legend.title.position = "top"), 
  #                       nrow = 2, byrow = TRUE)) +
  # ggspatial::annotation_north_arrow(location = "bl", data = subset(maplines, season == "POSTGUARD"), text_col = "white") +
  #  ggspatial::annotation_scale(location = "br", data = subset(maplines, season == "POSTGUARD"), text_col = "white") +
  scale_x_continuous(expand = c(0,0)) + # Adjust x-axis breaks
  scale_y_continuous(expand = c(0,0)) +
  theme_classic() +
  theme(legend.position = "none", 
        legend.box = "horizontal", 
        axis.text = element_text(size = 12),
        plot.margin = margin(0, 0, 0, 0)  # Remove white space around the plot
  ) 
pplot
```

```{r}
# Define the coordinate for Banks Peninsula, New Zealand (approximate)
banks_peninsula <- st_sfc(st_point(c(172.872, -43.800)), crs = 4326)

# Create a buffer of 100km around Banks Peninsula (sf object)
buffer_100km <- st_buffer(banks_peninsula, dist = 100000)  # 100 km in meters

# Plot the satellite image basemap using ggmap (OpenStreetMap satellite tiles)
# Note: No API is required in this case for basemap but we do need internet access for download.
# Specify the bounding box for Banks Peninsula
bbox <- st_bbox(buffer_100km)

# Download a satellite basemap (OpenStreetMap)
map <- ggmap::get_map(location = c(lon = mean(c(bbox["xmin"], bbox["xmax"])), 
                                   lat = mean(c(bbox["ymin"], bbox["ymax"]))),
                      zoom = 10, 
                      maptype = "satellite", source = "osm")

# Convert the 'sf' object to a data frame for ggplot
buffer_df <- st_as_sf(buffer_100km)

# Plot the map using ggplot
ggplot() +
  # Display satellite image base map
  annotation_raster(map, xmin = bbox["xmin"], xmax = bbox["xmax"], ymin = bbox["ymin"], ymax = bbox["ymax"]) +
  # Add the buffer polygon from the 'sf' object
  geom_sf(data = buffer_df, fill = NA, color = "red", size = 1) +
  # Customize the plot
  theme_minimal() +
  ggtitle("100km Buffer Around Banks Peninsula, NZ") +
  coord_sf(xlim = c(bbox["xmin"], bbox["xmax"]), ylim = c(bbox["ymin"], bbox["ymax"]), expand = FALSE)

```

