# ---
# title: "Pohatu Penguins GPS/TDR Data Prepare for Movebank upload
# author: "Rachel Hickcox"
# date: "2024"
# email: "rphickcox@gmail.com"
# ---


### Load packages 
```{r}
pkgs <- c("tidyverse", "here", "readxl")
invisible(lapply(pkgs, library, character.only = TRUE))
options(scipen = 999)
```


### Reading in text files
```{r}
folder_in <- "C:/Users/rphic/OneDrive/Documents/Pohatu_data/Breeding_2023"
files_list_in <- list.files(path = folder_in, pattern = "^[^DUD].+\\.txt$", full.names = FALSE)
files_list_full <- list.files(path = folder_in, pattern = "^[^DUD].+\\.txt$", full.names = TRUE)

deploy <- read_excel("C:/Users/rphic/OneDrive/Documents/Pohatu_data/GPS_tracking_metadata.xlsx", sheet = "Deployments 2023-2024")
deploy <- deploy[c(1, 8, 9)]
names(deploy) <- c("GPSID", "AnimalID", "NestID")
```

### Toread function
```{r}
getname <- function(files_list_in){
  nam <- unlist(strsplit(files_list_in, "_"))
  year <- unlist(strsplit(nam[[4]], "[.]"))
  year <- paste(str_sub(year[[1]], 1, 7 ))
  season <- paste(nam[[3]])
  season <- toupper(season)
  nb <- paste(nam[[1]])
  nam <- paste(nam[[2]])
  nam <- toupper(nam)
  c(tolower(nam), year, tolower(season), nb)
}

named <- lapply(files_list_in, getname)

# Convert xx to a dataframe
named <- data.frame(matrix(unlist(named), nrow = length(named), byrow = TRUE))
colnames(named) <- c("Name", "Year", "Season", "Nb")
```


```{r}
# Define a function to read each file
read_file <- function(i) {
  x <- read.delim(files_list_full[i], header = FALSE, strip.white = TRUE, blank.lines.skip = TRUE)  # Adjust this based on the format of your files
  names(x) <- c("Timestamp", "Latitude", "Longitude", "HeightAboveSL", "groundspeed", "Satellites", "HDOP", "SignalStrength")
  x <- x %>%
    mutate("Species" = "Eudyptula minor", 
           "AnimalID" = named[i,]$Name, 
           "Sensor" = "GPS") %>%
    left_join(deploy, by = "AnimalID")
  x
}

# Read in all the files using lapply
file_contents <- lapply(1:length(files_list_full), read_file)

# Combine the list of dataframes into a single dataframe using rbind
combined_df <- do.call(rbind, file_contents)
write.csv(combined_df, file.path(folder_in, "Alldata_movebank.csv"), row.names = FALSE)

```

 